behaviors:
  Company:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 12800
      learning_rate: 0.0003
      beta: 0.002
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 200000
    time_horizon: 512
    summary_freq: 10000
    threaded: false
  CompanySac:
    trainer_type: sac
    hyperparameters:
      batch_size: 512
      buffer_size: 12800
      learning_rate: 0.0003
      buffer_init_steps: 1000
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 100000
    time_horizon: 128
    summary_freq: 10000
  GovernmentNew:
    trainer_type: sac
    hyperparameters:
      batch_size: 512
      buffer_size: 12800
      learning_rate: 0.0003
      buffer_init_steps: 1000
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1000
    time_horizon: 56
    summary_freq: 10