behaviors:
  GovernmentNew:
    trainer_type: sac
    hyperparameters:
      batch_size: 512
      buffer_size: 12800
      learning_rate: 0.0003
      buffer_init_steps: 1000
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1000
    time_horizon: 56
    summary_freq: 100