behaviors:
  GovernmentNew:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 12800
      learning_rate: 0.0003
      beta: 0.002
      epsilon: 0.2
      lambd: 0.98
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 10
    max_steps: 500
    time_horizon: 128
    summary_freq: 10
    threaded: false